### ISSUE TITLE
Workflow fails with 'No need to run analysis. It is already triggered by the push event.'

### ISSUE THREAD

**Issue by sujitdmello** [kitabisa/sonarqube-action#12]
Works on initial PR open but after that if further commits are made or comments/changes made to the PR, the build fails

Only workaround is to close the PR and open a new one which is not ideal.

**Comment by dwisiswant0** [comment]
You can do that with:

```yaml
on: 
  pull_request:
```

**Comment by anaik-zam** [comment]
I'm getting the same 'No need to run analysis ...' message. I'm triggering the workflow when a pull request is opened or updated.
`on:
  pull_request:
    types: [opened, reopened, edited, synchronize]`
Shouldn't sonar qube scan run again when a pr is updated?
https://github.com/kitabisa/sonarqube-action/blob/master/entrypoint.sh#L7 should allow the other event types as well. I don't mind creating a PR
