### ISSUE TITLE
[Question] Its possible set binary java?

### ISSUE THREAD

**Issue by rafaelcorbellini-egsys** [kitabisa/sonarqube-action#15]
`org.sonar.java.AnalysisException: Your project contains .java files, please provide compiled classes with sonar.java.binaries property, or exclude them from the analysis with sonar.exclusions property.`

is there any way to set these property?   `sonar.java.binaries ` and  `sonar.exclusions property`

**Comment by dwisiswant0** [comment]
Since this workflow is built for a low-level, I recommend you to add `sonar-project.properties` file to add additional parameter analysis, @rafaelcorbellini-egsys.
