### ISSUE TITLE
Feature request: Option to not exit with an error when already analyzed

### ISSUE THREAD

**Issue by marcauberer** [kitabisa/sonarqube-action#16]
Following behaviour:
![image](https://user-images.githubusercontent.com/59527509/98559605-1ad54780-22a7-11eb-8905-02e4fab66f61.png)

Would be nice, if your action had the possibility to opt-out this failure.

To reproduce:
Open a pr as draft and push another commit. The sonaqube check of the second commit shows an error.

**Comment by dwisiswant0** [comment]
Hi @marcauberer, this should be fixed in `v1.1.0` version. Can you please give it try then we close it?

**Comment by marcauberer** [comment]
Wow, that was fast! And it's working like a charm. Thanks
