### ISSUE TITLE
java.lang.IllegalStateException: The plugin [icode] does not support Java 1.8.0_181

### ISSUE THREAD

**Issue by nehaprb** [kitabisa/sonarqube-action#18]
### Issue and Steps to Reproduce

I was able to get report using this action and below code.

on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectKey: "project_key"
        projectName: "project"

Now, all of sudden, it has started showing below error. How to overcome this error ?

INFO: SonarQube Scanner 4.0.0.1744
INFO: Java 1.8.0_181 Oracle Corporation (64-bit)
INFO: Linux 5.4.0-1031-azure amd64
INFO: User cache: /root/.sonar/cache
SonarQube server 8.4.2
SonarScanner will require Java 11 to run starting in SonarQube 8.x

java.lang.IllegalStateException: The plugin [icode] does not support Java 1.8.0_181
Caused by: ja_va.lang.UnsupportedClassVersionError: fr/cnes/sonar/plugins/icode/ICodePlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0**

**Comment by dwisiswant0** [comment]
Closing this issue because the problem you are facing is not from the workflow side.
