### ISSUE TITLE
Consider reopen activity on pull_request event

### ISSUE THREAD

**Issue by anasirvent** [kitabisa/sonarqube-action#21]
### Issue and Steps to Reproduce
I would like to run the action on a pull request event.
When the pull request is created the action runs fine and can fail if the quality gate of the project fails. However if you have a pull request job that fails because of sonar, you can close the pull request and reopen it again, the job will pass successfully without scanning saying "No need to run analysis. It is already triggered by the push event" because the reopen activity for the pull request event  is not considered in the entrypoint.sh

 ```
if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
	EVENT_ACTION=$(jq -r ".action" "${GITHUB_EVENT_PATH}")
	if [[ "${EVENT_ACTION}" != "opened" ]]; then
		echo "No need to run analysis. It is already triggered by the push event."
		exit
	fi
fi
```

### Versions
v1.1.0

**Comment by anasirvent** [comment]
Hey, it would be great if you can also add the "synchronize" activity, as it happens the same issue when the PR is updated with a new commit.

**Comment by rthewhite** [comment]
Created above pull #26 to run pull request scanning not only on opening but on edit/reopen/synchronize as well.
