### ISSUE TITLE
Any option to add sonar exclusions? 

### ISSUE THREAD

**Issue by akhil-intellect** [kitabisa/sonarqube-action#25]
Sonar have option to exclude folder from scan width ` sonar.exclusions ` . Do we have any option to add that ?

**Comment by akhil-intellect** [comment]
any update on this ?

**Comment by raag** [comment]
Hello @akhil-intellect in your project that you will analize you can create a file called `sonar-project.properties`

So, there you can specify files and directories you want to exclude, for example:

``` 
sonar-project.properties
```

**Comment by stefan2904** [comment]
> in your project that you will analize you can create a file called sonar-project.properties

that indeed works, but keep in mind that if that files exist, the action does not pass all properties to the sonar runner anymore:

https://github.com/kitabisa/sonarqube-action/blob/d7e1e2bb60a90b30c968c7953d7721f8dee880ec/entrypoint.sh#L21-L36
