### ISSUE TITLE
Sonar action fails with errors

### ISSUE THREAD

**Issue by 1633605** [kitabisa/sonarqube-action#28]
### Issue and Steps to Reproduce
Sonarscanner is failing with error saying that "not inside a Git work tree: /github/workspace". After seeing this added projectbase dir attribute with the path where the code has been checkout and it fails with "Project home must be an existing directory: /github/workspace"
### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by dwisiswant0** [comment]
I guess it's been fixed since the latest (v1.2.0) version.
