### ISSUE TITLE
Iam not really sure is this a bug but with solution (Could not find 'java' executable in JAVA_HOME or PATH.)

### ISSUE THREAD

**Issue by alexanderaucobo** [kitabisa/sonarqube-action#31]
### Issue and Steps to Reproduce
use actions/setup-java@v2
use kitabisa/sonarqube-action@v1.1.1
then this happens:

Could not find 'java' executable in JAVA_HOME or PATH.

Why this happens: It is overwriting the environment variables set in the docker container from sonar-scanner

How to fix it: Set environment variable for this action back to the env variable from the original docker container from sonar-scan ner

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.1.1
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}

Have a nice day :-)

**Comment by vinodbalakumar** [comment]
ERROR: Error during SonarScanner execution
org.sonar.java.AnalysisException: Your project contains .java files, please provide compiled classes with sonar.java.binaries property, or exclude them from the analysis with sonar.exclusions property.


I am facing the above issue could you pls share the configuration details? how to setup your lib for spring boot APP.
