### ISSUE TITLE
projectKey not read from sonar-project.properties

### ISSUE THREAD

**Issue by sebalopez** [kitabisa/sonarqube-action#5]
I run this action for a repository where I have defined a sonar-project.properties, in which I have defined: 

> `sonar.projectKey=my-project`

however during Action execution I can see the project key is always set to 'workspace' (overwriting results for any existing project with that key name):

> `INFO: Project key: workspace`

Other settings in sonar-project.properties seem to be read fine.
Is there a workaround for this behavior?

Thanks!

**Comment by achilleslinux** [comment]
In sonar-project.properties file you need to mention one more line

`sonar.projectName=MyNewProjectName`

**Comment by sebalopez** [comment]
Please do not close this, the response is not correct. I had set sonar.projectName, this property is showcased fine in Sonar, but still Project key is 'workspace'

**Comment by shreshtha1106** [comment]
I am facing the same problem

**Comment by jankal** [comment]
I also think, this Issue still persists. I have multiple projects with perfect sonar-project.properties files set up. And they do not seem to get read.

**Comment by dwisiswant0** [comment]
> I also think, this Issue still persists. I have multiple projects with perfect sonar-project.properties files set up. And they do not seem to get read.

Aight, I recommend you to create new issue. Since I think it has been fixed in the latest version, please also attach logs of the workflow.

**Comment by jankal** [comment]
@dwisiswant0 thanks for the response!
I will first try to fix this issue over at jankal/sonarqube-action and I will send PR when everything works.
